import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.scss";
import Navbar from "@/Layout/Navbar/Navbar";
import AsideMenu from "@/Layout/AsideMenu/AsideMenu";
import Footer from "@/Layout/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IQEA Estimador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {



  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <AsideMenu />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
